<a href="https://colab.research.google.com/github/greyhound101/Brain_tumour/blob/master/densenet_rmsprop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
drive.mount("/content/gdrive", force_remount=True)

Mounted at /content/gdrive
Mounted at /content/gdrive


In [7]:
import glob
glob.glob('/content/gdrive/My Drive/densenet/*rmsprop_0*')

['/content/gdrive/My Drive/densenet/best_accuracy_all_fold_2_densenet_rmsprop_0.npy',
 '/content/gdrive/My Drive/densenet/final_accuracy_all_fold2_densenet_rmsprop_0.npy',
 '/content/gdrive/My Drive/densenet/history_all_fold_2_densenet_rmsprop_0.npy',
 '/content/gdrive/My Drive/densenet/answers_all_fold_2_densenet_rmsprop_0.npy',
 '/content/gdrive/My Drive/densenet/predictions_all_fold_2_densenet_rmsprop_0.npy',
 '/content/gdrive/My Drive/densenet/predictions_all_best_fold_2_densenet_rmsprop_0.npy',
 '/content/gdrive/My Drive/densenet/times_all_fold_2_densenet_rmsprop_0.npy',
 '/content/gdrive/My Drive/densenet/final_predictions_2_densenet_rmsprop_0.npy',
 '/content/gdrive/My Drive/densenet/best_accuracy_all_fold_3_densenet_rmsprop_0.npy',
 '/content/gdrive/My Drive/densenet/final_accuracy_all_fold3_densenet_rmsprop_0.npy',
 '/content/gdrive/My Drive/densenet/history_all_fold_3_densenet_rmsprop_0.npy',
 '/content/gdrive/My Drive/densenet/answers_all_fold_3_densenet_rmsprop_0.npy',
 '/c

In [5]:

glob.glob('/content/gdrive/My Drive/densenet/*rsmprop_3*')

['/content/gdrive/My Drive/densenet/best_accuracy_all_fold_5_densenet_rsmprop_3.npy',
 '/content/gdrive/My Drive/densenet/final_accuracy_all_fold5_densenet_rsmprop_3.npy',
 '/content/gdrive/My Drive/densenet/history_all_fold_5_densenet_rsmprop_3.npy',
 '/content/gdrive/My Drive/densenet/answers_all_fold_5_densenet_rsmprop_3.npy',
 '/content/gdrive/My Drive/densenet/predictions_all_fold_5_densenet_rsmprop_3.npy',
 '/content/gdrive/My Drive/densenet/predictions_all_best_fold_5_densenet_rsmprop_3.npy',
 '/content/gdrive/My Drive/densenet/times_all_fold_5_densenet_rsmprop_3.npy',
 '/content/gdrive/My Drive/densenet/actual_predictions5_densenet_rsmprop_3.npy']

In [12]:
np.load( '/content/gdrive/My Drive/densenet/final_accuracy_all_fold5_densenet_rsmprop_3.npy',allow_pickle=True)

array({'fold_5': 0.9548989113530326}, dtype=object)

In [13]:
np.load(  '/content/gdrive/My Drive/densenet/final_accuracy_all_fold2_densenet_rmsprop_0.npy',allow_pickle=True)

array({'fold_2': 0.9528718703976435}, dtype=object)

In [14]:
np.load(  '/content/gdrive/My Drive/densenet/final_accuracy_all_fold3_densenet_rmsprop_0.npy',allow_pickle=True)

array({'fold_3': 0.965034965034965}, dtype=object)

In [74]:
import numpy as np
fold1=list(np.load('/content/actual_predictions1_1e-3_wn (1).npy'))
fold2=list(np.load(   '/content/gdrive/My Drive/densenet/final_predictions_2_densenet_rmsprop_0.npy'))
fold3=list(np.load(  '/content/gdrive/My Drive/densenet/final_predictions_3_densenet_rmsprop_0.npy'))
fold4=list(np.load('/content/actual_predictions4_1e-3_wn (1).npy'))
fold5=list(np.load(  '/content/gdrive/My Drive/densenet/actual_predictions5_densenet_rsmprop_3.npy'))
actual=fold1+fold2+fold3+fold4+fold5
fold1_pre=list(np.load('/content/predictions_last_fold1_1e-3_wn (1).npy',allow_pickle=True).item()['fold_1'])
fold2_pre=list(np.load(  '/content/gdrive/My Drive/densenet/predictions_all_fold_2_densenet_rmsprop_0.npy',allow_pickle=True).item()['fold_2'])
fold3_pre=list(np.load(  '/content/gdrive/My Drive/densenet/predictions_all_fold_3_densenet_rmsprop_0.npy',allow_pickle=True).item()['fold_3'])
fold4_pre=list(np.load('/content/predictions_last_fold4_1e-3_wn (1).npy',allow_pickle=True).item()['fold_4'])
fold5_pre=list(np.load(  '/content/gdrive/My Drive/densenet/predictions_all_fold_5_densenet_rsmprop_3.npy',allow_pickle=True).item()['fold_5'])

predicted=fold1_pre+fold2_pre+fold3_pre+fold4_pre+fold5_pre

In [75]:
len(actual),len(predicted)

(3064, 3064)

In [77]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(actual, predicted)

(array([0.9279661 , 0.96999302, 0.96966414]),
 array([0.9279661 , 0.97475456, 0.96236559]),
 array([0.9279661 , 0.97236796, 0.96600108]),
 array([ 708, 1426,  930]))

In [78]:
from sklearn.metrics import confusion_matrix
confusion_matrix(actual,predicted)

array([[ 657,   29,   22],
       [  30, 1390,    6],
       [  21,   14,  895]])

In [88]:
0.9799777638321746:specificity

0.9783531409168081