<a href="https://colab.research.google.com/github/greyhound101/Brain_tumour/blob/master/densenet_sgd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
drive.mount("/content/gdrive", force_remount=True)

Mounted at /content/gdrive
Mounted at /content/gdrive


In [4]:
import glob
glob.glob('/content/gdrive/My Drive/densenet/*sgd*')

['/content/gdrive/My Drive/densenet/times_all_fold_4_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/history_all_fold_4_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/predictions_all_best_fold_4_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/predictions_all_fold_4_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/final_accuracy_all_fold4_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/best_accuracy_all_fold_4_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/answers_all_fold_4_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/final_accuracy_all_fold5_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/best_accuracy_all_fold_5_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/predictions_all_best_fold_5_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/answers_all_fold_5_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/history_all_fold_5_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/predictions_all_fold_5_densenet_

In [6]:
import numpy as np
fold1=list(np.load('/content/actual_predictions1_1e-3_wn (5).npy'))
fold2=list(np.load(    '/content/gdrive/My Drive/densenet/actual_predictions_2_densenet_sgd.npy',allow_pickle=True))
fold3=list(np.load(   '/content/gdrive/My Drive/densenet/actual_predictions3_densenet_sgd.npy',allow_pickle=True))
fold4=list(np.load('/content/actual_predictions4_1e-3_wn (4).npy'))
fold5=list(np.load(  '/content/actual_predictions5_1e-3_wn (4).npy'))
actual=fold1+fold2+fold3+fold4+fold5
fold1_pre=list(np.load('/content/predictions_last_fold1_1e-3_wn (5).npy',allow_pickle=True).item()['fold_1'])
fold2_pre=list(np.load(  '/content/gdrive/My Drive/densenet/predictions_all_fold_2_densenet_sgd.npy',allow_pickle=True).item()['fold_2'])
fold3_pre=list(np.load(  '/content/gdrive/My Drive/densenet/predictions_all_fold_3_densenet_sgd.npy',allow_pickle=True).item()['fold_3'])
fold4_pre=list(np.load('/content/predictions_last_fold4_1e-3_wn (4).npy',allow_pickle=True).item()['fold_4'])
fold5_pre=list(np.load(  '/content/predictions_last_fold5_1e-3_wn (4).npy',allow_pickle=True).item()['fold_5'])

predicted=fold1_pre+fold2_pre+fold3_pre+fold4_pre+fold5_pre

In [ ]:
specificity:0.9720398273862706

In [7]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(actual, predicted)

(array([0.67371202, 0.85998526, 0.78736842]),
 array([0.72033898, 0.81837307, 0.80430108]),
 array([0.69624573, 0.83866331, 0.79574468]),
 array([ 708, 1426,  930]))

In [8]:
from sklearn.metrics import confusion_matrix
confusion_matrix(actual,predicted)

array([[ 510,  102,   96],
       [ 153, 1167,  106],
       [  94,   88,  748]])

In [9]:
(1167+194+748)/(1167+194+748+198)

0.9141742522756827

In [10]:
(510+748+190)/(510+748+190+259)

0.8482718219097832

In [11]:
(510+1167+255)/(510+1167+255+182)

0.9139072847682119

In [12]:
(0.9141742522756827+0.8482718219097832+0.9139072847682119)/3

0.8921177863178927