<a href="https://colab.research.google.com/github/greyhound101/Brain_tumour/blob/master/densenet_sgd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
drive.mount("/content/gdrive", force_remount=True)

Mounted at /content/gdrive
Mounted at /content/gdrive


In [92]:
import glob
glob.glob('/content/gdrive/My Drive/densenet/*sgd*')

['/content/gdrive/My Drive/densenet/times_all_fold_4_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/history_all_fold_4_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/predictions_all_best_fold_4_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/predictions_all_fold_4_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/final_accuracy_all_fold4_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/best_accuracy_all_fold_4_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/answers_all_fold_4_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/final_accuracy_all_fold5_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/best_accuracy_all_fold_5_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/predictions_all_best_fold_5_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/answers_all_fold_5_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/history_all_fold_5_densenet_sgd.npy',
 '/content/gdrive/My Drive/densenet/predictions_all_fold_5_densenet_

In [5]:

glob.glob('/content/gdrive/My Drive/densenet/*rsmprop_3*')

['/content/gdrive/My Drive/densenet/best_accuracy_all_fold_5_densenet_rsmprop_3.npy',
 '/content/gdrive/My Drive/densenet/final_accuracy_all_fold5_densenet_rsmprop_3.npy',
 '/content/gdrive/My Drive/densenet/history_all_fold_5_densenet_rsmprop_3.npy',
 '/content/gdrive/My Drive/densenet/answers_all_fold_5_densenet_rsmprop_3.npy',
 '/content/gdrive/My Drive/densenet/predictions_all_fold_5_densenet_rsmprop_3.npy',
 '/content/gdrive/My Drive/densenet/predictions_all_best_fold_5_densenet_rsmprop_3.npy',
 '/content/gdrive/My Drive/densenet/times_all_fold_5_densenet_rsmprop_3.npy',
 '/content/gdrive/My Drive/densenet/actual_predictions5_densenet_rsmprop_3.npy']

In [12]:
np.load( '/content/gdrive/My Drive/densenet/final_accuracy_all_fold5_densenet_rsmprop_3.npy',allow_pickle=True)

array({'fold_5': 0.9548989113530326}, dtype=object)

In [13]:
np.load(  '/content/gdrive/My Drive/densenet/final_accuracy_all_fold2_densenet_rmsprop_0.npy',allow_pickle=True)

array({'fold_2': 0.9528718703976435}, dtype=object)

In [14]:
np.load(  '/content/gdrive/My Drive/densenet/final_accuracy_all_fold3_densenet_rmsprop_0.npy',allow_pickle=True)

array({'fold_3': 0.965034965034965}, dtype=object)

In [102]:
import numpy as np
fold1=list(np.load('/content/actual_predictions1_1e-3_wn (2).npy'))
fold2=list(np.load(   '/content/gdrive/My Drive/densenet/predictions_all_fold_2_densenet_sgd.npy',allow_pickle=True).item()['fold_2'])
fold3=list(np.load(  '/content/gdrive/My Drive/densenet/predictions_all_fold_3_densenet_sgd.npy',allow_pickle=True).item()['fold_3'])
fold4=list(np.load('/content/actual_predictions4_1e-3_wn (2).npy'))
fold5=list(np.load(  '/content/actual_predictions5_1e-3_wn (1).npy'))
actual=fold1+fold2+fold3+fold4+fold5
fold1_pre=list(np.load('/content/predictions_last_fold1_1e-3_wn (2).npy',allow_pickle=True).item()['fold_1'])
fold2_pre=list(np.load(  '/content/gdrive/My Drive/densenet/predictions_all_fold_2_densenet_sgd.npy',allow_pickle=True).item()['fold_2'])
fold3_pre=list(np.load(  '/content/gdrive/My Drive/densenet/predictions_all_fold_3_densenet_sgd.npy',allow_pickle=True).item()['fold_3'])
fold4_pre=list(np.load('/content/predictions_last_fold4_1e-3_wn (2).npy',allow_pickle=True).item()['fold_4'])
fold5_pre=list(np.load(  '/content/predictions_last_fold5_1e-3_wn (1).npy',allow_pickle=True).item()['fold_5'])

predicted=fold1_pre+fold2_pre+fold3_pre+fold4_pre+fold5_pre

In [ ]:
specificity:0.9720398273862706

In [103]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(actual, predicted)

(array([0.87978864, 0.97715549, 0.95368421]),
 array([0.90859482, 0.94917681, 0.97002141]),
 array([0.89395973, 0.96296296, 0.96178344]),
 array([ 733, 1397,  934]))

In [104]:
from sklearn.metrics import confusion_matrix
confusion_matrix(actual,predicted)

array([[ 666,   26,   41],
       [  68, 1326,    3],
       [  23,    5,  906]])

In [105]:
(1326+8+906)/(1326+8+906+67)

0.9709579540528825

In [109]:
(906+666+64)/(906+666+64+71)

0.958406561218512

In [108]:
(1326+666+94)/(1326+666+94+28)

0.9867549668874173

In [110]:
(0.9709579540528825+0.958406561218512+0.9867549668874173)/3

0.9720398273862706