<a href="https://colab.research.google.com/github/greyhound101/Brain_tumour/blob/master/inception_sgd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
drive.mount("/content/gdrive", force_remount=True)

Mounted at /content/gdrive
Mounted at /content/gdrive


In [3]:
import numpy as np
fold1=list(np.load('/content/actual_predictions1_1e-3_wn (4).npy'))
fold2=list(np.load(   '/content/actual_predictions2_1e-3_wn (2).npy'))
fold3=list(np.load(  '/content/actual_predictions3_1e-3_wn (1).npy'))
fold4=list(np.load( '/content/actual_predictions4_1e-3_wn (3).npy'))
fold5=list(np.load(  '/content/actual_predictions5_1e-3_wn (3).npy'))
actual=fold1+fold2+fold3+fold4+fold5
fold1_pre=list(np.load('/content/predictions_last_fold1_1e-3_wn (4).npy',allow_pickle=True).item()['fold_1'])
fold2_pre=list(np.load(  '/content/predictions_last_fold2_1e-3_wn (2).npy',allow_pickle=True).item()['fold_2'])
fold3_pre=list(np.load(  '/content/predictions_last_fold3_1e-3_wn (1).npy',allow_pickle=True).item()['fold_3'])
fold4_pre=list(np.load( '/content/predictions_last_fold4_1e-3_wn (3).npy',allow_pickle=True).item()['fold_4'])
fold5_pre=list(np.load(  '/content/predictions_last_fold5_1e-3_wn (3).npy',allow_pickle=True).item()['fold_5'])

predicted=fold1_pre+fold2_pre+fold3_pre+fold4_pre+fold5_pre

In [4]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(actual, predicted)

(array([0.78061911, 0.93222783, 0.93576017]),
 array([0.81920904, 0.90673212, 0.93978495]),
 array([0.79944866, 0.91930323, 0.93776824]),
 array([ 708, 1426,  930]))

In [5]:
from sklearn.metrics import confusion_matrix
confusion_matrix(actual,predicted)

array([[ 580,   72,   56],
       [ 129, 1293,    4],
       [  34,   22,  874]])

In [6]:
(1293+874+26)/(1293+874+26+128)

0.944851357173632

In [7]:
(580+874+90)/(580+874+90+133)

0.9206917113893858

In [8]:
(1293+580+201)/(1293+580+201+56)

0.9737089201877934

In [9]:
(0.944851357173632+0.9737089201877934+0.9206917113893858)/3

0.9464173295836037