<a href="https://colab.research.google.com/github/greyhound101/Brain_tumour/blob/master/inception_rmsprop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
drive.mount("/content/gdrive", force_remount=True)

Mounted at /content/gdrive
Mounted at /content/gdrive


In [2]:
import glob
glob.glob('/content/gdrive/My Drive/inception/*rmsprop_final*')

['/content/gdrive/My Drive/inception/best_accuracy_all_fold_4_inception_rmsprop_final.npy',
 '/content/gdrive/My Drive/inception/final_accuracy_all_fold4_inception_rmsprop_final.npy',
 '/content/gdrive/My Drive/inception/history_all_fold_4_inception_rmsprop_final.npy',
 '/content/gdrive/My Drive/inception/answers_all_fold_4_inception_rmsprop_final.npy',
 '/content/gdrive/My Drive/inception/predictions_all_fold_4_inception_rmsprop_final.npy',
 '/content/gdrive/My Drive/inception/predictions_all_best_fold_4_inception_rmsprop_final.npy',
 '/content/gdrive/My Drive/inception/times_all_fold_4_inception_rmsprop_final.npy',
 '/content/gdrive/My Drive/inception/actual_predictions_4_inception_rmsprop_final.npy']

In [5]:
import numpy as np
fold1=list(np.load('/content/actual_predictions1_1e-3_wn (3).npy'))
fold2=list(np.load(   '/content/actual_predictions2_1e-3_wn (1).npy'))
fold3=list(np.load(  '/content/actual_predictions3_1e-3_wn.npy'))
fold4=list(np.load( '/content/gdrive/My Drive/inception/actual_predictions_4_inception_rmsprop_final.npy'))
fold5=list(np.load(  '/content/actual_predictions5_1e-3_wn (2).npy'))
actual=fold1+fold2+fold3+fold4+fold5
fold1_pre=list(np.load('/content/predictions_last_fold1_1e-3_wn (3).npy',allow_pickle=True).item()['fold_1'])
fold2_pre=list(np.load(  '/content/predictions_last_fold2_1e-3_wn (1).npy',allow_pickle=True).item()['fold_2'])
fold3_pre=list(np.load(  '/content/predictions_last_fold3_1e-3_wn.npy',allow_pickle=True).item()['fold_3'])
fold4_pre=list(np.load( '/content/gdrive/My Drive/inception/predictions_all_fold_4_inception_rmsprop_final.npy',allow_pickle=True).item()['fold_4'])
fold5_pre=list(np.load(  '/content/predictions_last_fold5_1e-3_wn (2).npy',allow_pickle=True).item()['fold_5'])

predicted=fold1_pre+fold2_pre+fold3_pre+fold4_pre+fold5_pre

In [6]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(actual, predicted)

(array([0.90013495, 0.98210451, 0.96436285]),
 array([0.9420904 , 0.96213184, 0.96021505]),
 array([0.92063492, 0.97201559, 0.96228448]),
 array([ 708, 1426,  930]))

In [7]:
from sklearn.metrics import confusion_matrix
confusion_matrix(actual,predicted)

array([[ 667,   15,   26],
       [  47, 1372,    7],
       [  27,   10,  893]])

In [8]:
(1372+893)/(1372+893+41)

0.9822202948829142

In [10]:
(667+893+53)/(667+893+53+54)

0.9676064787042592

In [11]:
(667+1372+62)/(667+1372+62+37)

0.9826941066417212

In [12]:
(0.9822202948829142+0.9676064787042592+0.9826941066417212)/3

0.9775069600762981